stages:
  - build
  - test
  - deploy

.template-test-gcc:
  stage: test
  image: $CI_IMAGE_GCC:12
  script:
    - make check

build-gcc:
  stage: build
  image: $IMAGE
  script:
    - make all CC=gcc
  artifacts:
    paths:
      - build/
      - test/build/
  parallel:
    matrix:
      - IMAGE: [
          "$CI_IMAGE_GCC:7",
          "$CI_IMAGE_GCC:8",
          "$CI_IMAGE_GCC:9",
          "$CI_IMAGE_GCC:10",
          "$CI_IMAGE_GCC:11",
          "$CI_IMAGE_GCC:12"
        ]

test-gcc-7:
  extends: .template-test-gcc
  needs: ["build-gcc: [$CI_IMAGE_GCC:7]"]

test-gcc-8:
  extends: .template-test-gcc
  needs: ["build-gcc: [$CI_IMAGE_GCC:8]"]

test-gcc-9:
  extends: .template-test-gcc
  needs: ["build-gcc: [$CI_IMAGE_GCC:9]"]

test-gcc-10:
  extends: .template-test-gcc
  needs: ["build-gcc: [$CI_IMAGE_GCC:10]"]

test-gcc-11:
  extends: .template-test-gcc
  needs: ["build-gcc: [$CI_IMAGE_GCC:11]"]

test-gcc-12:
  extends: .template-test-gcc
  needs: ["build-gcc: [$CI_IMAGE_GCC:12]"]

pages:
  stage: deploy
  image: $CI_IMAGE_DOXYGEN:latest
  script:
    - make doc
    - mv doc/doxygen/html public
  artifacts:
    paths:
      - public
  dependencies: []
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
